### ISSUE TITLE
Vectorによる視点変更が失敗する

### ISSUE THREAD

**Issue by Osmium1008** [Paken3DGameProject/SnowFight#34]
https://github.com/Paken3DGameProject/SnowFight/commit/eb40403668bffe9b0c79dcf24dd9b0b508080c0c
にてVectorを使った視点変更を試みていますが成功していません

**Comment by Osmium1008** [comment]
https://github.com/Paken3DGameProject/SnowFight/commit/1bc8ac65f1c252766bda36816c3847de2d2eefa7
画面表示はされるようにしましたが上下挙動が不安定です

**Comment by ageprocpp** [comment]
帰ったら適当に直します

2019年9月8日(日) 13:29 Osmium_1008 <notifications@github.com>:

**Comment by Osmium1008** [comment]
Cursorを色々やっていますがここはできる限り変えないようにしてください

**Comment by Osmium1008** [comment]
Cursorを色々やっていますがここはできる限り変えないようにしてください

**Comment by ageprocpp** [comment]
cursorは元々ウィンドウ上の相対座標(原点がウィンドウの中心で縦横が2の長さ)を出してそこから操作をしてるので、座標を出すパートまでは変更しないでください
今後の利用価値が高いので

2019年9月8日(日) 13:35 Osmium_1008 <notifications@github.com>:

**Comment by Osmium1008** [comment]
lastCursorPosというものがもともとのcursorと同じ感じになってます(cursorとは別に操作用の関数を作成するべきなのでしょうか...

**Comment by ageprocpp** [comment]
Discordでcapra氏も言ってましたが、絶対的なカーソルの位置から一意に回転角を決めるのが1番楽です
そうでないと一度ずれたら直らないので

2019年9月8日(日) 13:38 Osmium_1008 <notifications@github.com>:

**Comment by Osmium1008** [comment]
横方向の幅の問題を解決するためにゲーム画面の中央でカーソルを固定してそこからの動いた距離で決めようとしているためなのでできれば相対的にやりたいです

**Comment by ageprocpp** [comment]
じゃあ実装しといてください

2019年9月8日(日) 14:03 Osmium_1008 <notifications@github.com>:
